"""Helpers for normalizing query candidates generated by the model."""

from __future__ import annotations

import re


def finalize_queries(
    raw_queries: list[str],
    fallback_query: str,
    limit: int = 5,
) -> list[str]:
    candidates = [fallback_query, *raw_queries]
    deduped_queries: list[str] = []
    seen: set[str] = set()

    for candidate in candidates:
        normalized_candidate = _normalize_candidate(candidate)
        if not normalized_candidate:
            continue

        key = normalized_candidate.lower()
        if key in seen:
            continue

        seen.add(key)
        deduped_queries.append(normalized_candidate)

        if len(deduped_queries) >= limit:
            break

    return deduped_queries


def parse_query_lines(raw_text: str) -> list[str]:
    lines = [line.strip() for line in raw_text.splitlines()]
    parsed_lines: list[str] = []

    for line in lines:
        if not line:
            continue

        cleaned_line = re.sub(r"^\d+[\).\s-]*", "", line).strip()
        cleaned_line = cleaned_line.lstrip("-* ").strip()
        cleaned_line = cleaned_line.strip('"')
        if cleaned_line:
            parsed_lines.append(cleaned_line)

    return parsed_lines


def _normalize_candidate(candidate: str) -> str:
    normalized_candidate = " ".join(candidate.split())
    if not normalized_candidate:
        return ""

    normalized_candidate = normalized_candidate.strip('"')
    return normalized_candidate
